package net.sdvn.nascommon.db.objecbox;


import androidx.annotation.Keep;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BACKUP_INFO".
 */
@Keep
@Entity
public class BackupInfo {

    @Id
    private Long id;
    private String userId;
    private Long uid;
    private Integer type;
    private Long count;
    private Long time;
    private String devUUID;

    public BackupInfo() {
    }

    public BackupInfo(Long id) {
        this.id = id;
    }

    public BackupInfo(Long id, Long uid, Integer type, Long count, Long time) {
        this.id = id;
        this.uid = uid;
        this.type = type;
        this.count = count;
        this.time = time;
    }

    public BackupInfo(Long id, String devUUID, Integer type, Long count, Long time) {
        this.id = id;
        this.devUUID = devUUID;
        this.type = type;
        this.count = count;
        this.time = time;
    }

    public BackupInfo(Long id, Long uid, Integer type, Long count, Long time, String devUUID) {
        this.id = id;
        this.uid = uid;
        this.type = type;
        this.count = count;
        this.time = time;
        this.devUUID = devUUID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getDevUUID() {
        return this.devUUID;
    }

    public void setDevUUID(String devUUID) {
        this.devUUID = devUUID;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}
