package net.sdvn.nascommon.db.objecbox;


import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import java.util.Objects;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BACKUP_FILE".
 */
@Keep
@Entity
public class BackupFile {

    @Id
    private Long id;
    private String userId;
    //    private Long uid;
    private String devUUID;
    /*本地路径*/
    @NonNull
    private String path;
    //    是否自动备份
    private Boolean auto;
    /**
     * @see {link}BackupType
     */
    private Integer type;
    /**
     * @see {link}BackupPriority
     */
    private Integer priority;
    private Long time;
    private Long count;

    public BackupFile(Long id, String devUUID, @NonNull String path, Boolean auto, Integer type,
                      Integer priority, Long time, Long count) {
        this.id = id;
        this.devUUID = devUUID;
        this.path = path;
        this.auto = auto;
        this.type = type;
        this.priority = priority;
        this.time = time;
        this.count = count;
    }

    public BackupFile() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDevUUID() {
        return this.devUUID;
    }

    public void setDevUUID(String devUUID) {
        this.devUUID = devUUID;
    }

    @NonNull
    public String getPath() {
        return this.path;
    }

    public void setPath(@NonNull String path) {
        this.path = path;
    }

    public Boolean getAuto() {
        return this.auto;
    }

    public void setAuto(Boolean auto) {
        this.auto = auto;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getPriority() {
        return this.priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public Long getTime() {
        return this.time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Long getCount() {
        return this.count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BackupFile that = (BackupFile) o;
        return Objects.equals(devUUID, that.devUUID) &&
                Objects.equals(path, that.path);
    }

    @Override
    public int hashCode() {
        return Objects.hash(devUUID, path);
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}
