package net.sdvn.nascommon.db.objecbox;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import net.sdvn.nascommon.db.converter.IntroductionContentConverter;

import io.objectbox.annotation.Convert;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Unique;
import io.weline.repo.data.model.DataDevIntroduction;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DEVICE_INFO".
 */
@Keep
@Entity
public class DeviceInfo {

    @Id
    private long id;
    @NonNull
    @Unique
    private String mac;
    private String deviceSN;
    private String name;
    private String lanIp;
    private String lanPort;
    private String wanIp;
    private String wanPort;
    private String ssudpCid;
    private String ssudpPwd;
    private Integer domain;
    private Long time;
    private String vIp;
    private String vipPort;
    private String markName;
    private String markDesc;

    private String iconCacheKey;
    @Convert(converter =IntroductionContentConverter.class,dbType = String.class)
    private DataDevIntroduction devIntroduction;
//    @Transient
//    private DataDevIntroduction dataDevIntroduction;

    public DeviceInfo() {
    }

    public DeviceInfo(@NonNull String mac) {
        this.mac = mac;
    }

    public DeviceInfo(@NonNull String mac, String name, String lanIp, String lanPort, String wanIp, String wanPort, String ssudpCid, String ssudpPwd, Integer domain, Long time, String vIp, String vipPort, String markName,
                      String markDesc) {
        this.mac = mac;
        this.name = name;
        this.lanIp = lanIp;
        this.lanPort = lanPort;
        this.wanIp = wanIp;
        this.wanPort = wanPort;
        this.ssudpCid = ssudpCid;
        this.ssudpPwd = ssudpPwd;
        this.domain = domain;
        this.time = time;
        this.vIp = vIp;
        this.vipPort = vipPort;
        this.markName = markName;
        this.markDesc = markDesc;
    }

    @NonNull
    public String getMac() {
        return mac;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setMac(@NonNull String mac) {
        this.mac = mac;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLanIp() {
        return lanIp;
    }

    public void setLanIp(String lanIp) {
        this.lanIp = lanIp;
    }

    public String getLanPort() {
        return lanPort;
    }

    public void setLanPort(String lanPort) {
        this.lanPort = lanPort;
    }

    public String getWanIp() {
        return wanIp;
    }

    public void setWanIp(String wanIp) {
        this.wanIp = wanIp;
    }

    public String getWanPort() {
        return wanPort;
    }

    public void setWanPort(String wanPort) {
        this.wanPort = wanPort;
    }

    public String getSsudpCid() {
        return ssudpCid;
    }

    public void setSsudpCid(String ssudpCid) {
        this.ssudpCid = ssudpCid;
    }

    public String getSsudpPwd() {
        return ssudpPwd;
    }

    public void setSsudpPwd(String ssudpPwd) {
        this.ssudpPwd = ssudpPwd;
    }

    public Integer getDomain() {
        return domain;
    }

    public void setDomain(Integer domain) {
        this.domain = domain;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getVIp() {
        return vIp;
    }

    public void setVIp(String vIp) {
        this.vIp = vIp;
    }

    public String getVipPort() {
        return vipPort;
    }

    public void setVipPort(String vipPort) {
        this.vipPort = vipPort;
    }

    public String getMarkName() {
        return markName;
    }

    public void setMarkName(String markName) {
        this.markName = markName;
    }

    public String getMarkDesc() {
        return markDesc;
    }

    public void setMarkDesc(String markDesc) {
        this.markDesc = markDesc;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getDeviceSN() {
        return deviceSN;
    }

    public void setDeviceSN(String deviceSN) {
        this.deviceSN = deviceSN;
    }

    public String getIconCacheKey() {
        return iconCacheKey;
    }

    public void setIconCacheKey(String iconCacheKey) {
        this.iconCacheKey = iconCacheKey;
    }

    public @Nullable DataDevIntroduction getDevIntroduction() {
        return devIntroduction;
    }

    public void setDevIntroduction(@Nullable DataDevIntroduction devIntroduction) {
        this.devIntroduction = devIntroduction;
    }

//    @Nullable
//    public DataDevIntroduction getDataDevIntroduction() {
//        return converter.convertToEntityProperty(this.devIntroduction);
//    }
//
//    @Transient
//    private IntroductionContentConverter converter = new IntroductionContentConverter();
//
//    public void setDataDevIntroduction(@Nullable DataDevIntroduction dataDevIntroduction) {
//        this.dataDevIntroduction = dataDevIntroduction;
//        this.devIntroduction = converter.convertToDatabaseValue(dataDevIntroduction);
//    }
}
