package net.sdvn.nascommon.db.objecbox;


import androidx.annotation.Keep;

import net.sdvn.nascommon.db.converter.StringListConverter;

import java.util.List;

import io.objectbox.annotation.Convert;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER_SETTINGS".
 */
@Keep
@Entity
public class DeviceSettings {

    @Id
    private long uid;
    private String userId;
    private String devId;
    private Boolean isAutoBackupFile;
    private Boolean isAutoBackupAlbum;
    private Boolean isBackupFileOnlyWifi;
    private Boolean isBackupAlbumOnlyWifi;
    private Integer fileOrderType;
    private Integer fileViewerType;
    private Long time;
    @Convert(converter = StringListConverter.class, dbType = String.class)
    private List<String> backupAlbumPaths;

    public DeviceSettings() {
    }

    public DeviceSettings(String devId) {
        this.devId = devId;
    }

    public DeviceSettings(String devId, String downloadPath, String shareDownloadPath, Boolean isAutoBackupFile, Boolean isAutoBackupAlbum, Boolean isPreviewPicOnlyWifi, Boolean isTipTransferNotWifi, Boolean isBackupFileOnlyWifi, Boolean isBackupAlbumOnlyWifi, Integer fileOrderType,
                          Integer fileViewerType, Long time) {
        this.devId = devId;
        this.isAutoBackupFile = isAutoBackupFile;
        this.isAutoBackupAlbum = isAutoBackupAlbum;
        this.isBackupFileOnlyWifi = isBackupFileOnlyWifi;
        this.isBackupAlbumOnlyWifi = isBackupAlbumOnlyWifi;
        this.fileOrderType = fileOrderType;
        this.fileViewerType = fileViewerType;
        this.time = time;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }


    public Boolean getIsAutoBackupFile() {
        return isAutoBackupFile;
    }

    public void setIsAutoBackupFile(Boolean isAutoBackupFile) {
        this.isAutoBackupFile = isAutoBackupFile;
    }

    public Boolean getIsAutoBackupAlbum() {
        return isAutoBackupAlbum;
    }

    public void setIsAutoBackupAlbum(Boolean isAutoBackupAlbum) {
        this.isAutoBackupAlbum = isAutoBackupAlbum;
    }


    public Boolean getIsBackupFileOnlyWifi() {
        return isBackupFileOnlyWifi;
    }

    public void setIsBackupFileOnlyWifi(Boolean isBackupFileOnlyWifi) {
        this.isBackupFileOnlyWifi = isBackupFileOnlyWifi;
    }

    public Boolean getIsBackupAlbumOnlyWifi() {
        return isBackupAlbumOnlyWifi;
    }

    public void setIsBackupAlbumOnlyWifi(Boolean isBackupAlbumOnlyWifi) {
        this.isBackupAlbumOnlyWifi = isBackupAlbumOnlyWifi;
    }

    public Integer getFileOrderType() {
        return fileOrderType;
    }

    public void setFileOrderType(Integer fileOrderType) {
        this.fileOrderType = fileOrderType;
    }

    public Integer getFileViewerType() {
        return fileViewerType;
    }

    public void setFileViewerType(Integer fileViewerType) {
        this.fileViewerType = fileViewerType;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }


    public String getDevId() {
        return devId;
    }

    public void setDevId(String devId) {
        this.devId = devId;
    }


    public List<String> getBackupAlbumPaths() {
        return backupAlbumPaths;
    }

    public void setBackupAlbumPaths(List<String> backupAlbumPaths) {
        this.backupAlbumPaths = backupAlbumPaths;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}
