package net.sdvn.nascommon.db.objecbox;


import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import net.sdvn.nascommon.model.oneos.transfer.TransferState;

import java.util.Objects;

import io.objectbox.annotation.Convert;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Transient;

import static net.sdvn.nascommon.db.TransferHistoryKeeper.getTransferType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TRANSFER_HISTORY".
 */
@Keep
@Entity
public class TransferHistory {
    @Transient
    public final static int TYPE_DOWNLOAD = 1;
    @Transient
    public final static int TYPE_UPLOAD = 2;
    @Id
    private Long id;
    private String uid;
    private Integer type;
    private String userId;
    @NonNull
    private String name;

    @NonNull
    private String srcPath;
    //from or to
    private String srcDevId;

    @NonNull
    private String toPath;
    private Long size;
    private Long length;
    private Long duration;
    private Long time;
    private Boolean isComplete;
    private String tmpName;
    private int feature;
    private boolean check;
    @Nullable
    private Long groupId;
    @Convert(converter = TransferState.TransferStateConverter.class, dbType = String.class)
    private TransferState state = TransferState.WAIT;
    // order by State

    private int status = state.ordinal();

    public TransferHistory(Long id, String uid, Integer type, @NonNull String name,
                           @NonNull String srcPath, String srcDevId, @NonNull String toPath, Long size, Long length,
                           Long duration, Long time, Boolean isComplete, String tmpName

    ) {
        this(id, uid, type, name, srcPath, srcDevId, toPath, size, length, duration, time, isComplete, tmpName, false, null);
    }

    public TransferHistory(Long id, String uid, Integer type, @NonNull String name,
                           @NonNull String srcPath, String srcDevId, @NonNull String toPath, Long size, Long length,
                           Long duration, Long time, Boolean isComplete, String tmpName
            , boolean check
            , @Nullable Long groupId) {
        this.id = id;
        this.uid = uid;
        this.type = type;
        this.name = name;
        this.srcPath = srcPath;
        this.srcDevId = srcDevId;
        this.toPath = toPath;
        this.size = size;
        this.length = length;
        this.duration = duration;
        this.time = time;
        this.isComplete = isComplete;
        this.tmpName = tmpName;
        this.check = check;
        this.groupId = groupId;
    }

    public TransferHistory() {
    }

    public String getTag() {
        if (getTransferType(true) == getType()) {
            return getSrcDevId() + getSrcPath() + getToPath();
        } else {
            return getSrcPath() + getSrcDevId() + getToPath();
        }
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @NonNull
    public String getName() {
        return this.name;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }

    @NonNull
    public String getSrcPath() {
        return this.srcPath;
    }

    public void setSrcPath(@NonNull String srcPath) {
        this.srcPath = srcPath;
    }

    public String getSrcDevId() {
        return this.srcDevId;
    }

    public void setSrcDevId(String srcDevId) {
        this.srcDevId = srcDevId;
    }

    @NonNull
    public String getToPath() {
        return this.toPath;
    }

    public void setToPath(@NonNull String toPath) {
        this.toPath = toPath;
    }

    public Long getSize() {
        return this.size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public Long getLength() {
        return this.length;
    }

    public void setLength(Long length) {
        this.length = length;
    }

    public Long getDuration() {
        return this.duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public Long getTime() {
        return this.time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Boolean getIsComplete() {
        return this.isComplete;
    }

    public void setIsComplete(Boolean isComplete) {
        this.isComplete = isComplete;
    }

    public String getTmpName() {
        return this.tmpName;
    }

    public void setTmpName(String tmpName) {
        this.tmpName = tmpName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TransferHistory)) return false;
        TransferHistory that = (TransferHistory) o;
        return Objects.equals(id, that.id) &&
                Objects.equals(uid, that.uid) &&
                Objects.equals(type, that.type) &&
                name.equals(that.name) &&
                srcPath.equals(that.srcPath) &&
                Objects.equals(srcDevId, that.srcDevId) &&
                toPath.equals(that.toPath) &&
                Objects.equals(size, that.size) &&
                Objects.equals(isComplete, that.isComplete);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, uid, type, name, srcPath, srcDevId, toPath, size, isComplete);
    }

    public TransferState getState() {
        return state;
    }

    public void setState(TransferState state) {
        this.state = state;
    }


    public int getFeature() {
        return feature;
    }

    public void setFeature(int feature) {
        this.feature = feature;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public boolean isDownload() {
        return type == TYPE_DOWNLOAD;
    }

    public int getStatus() {
        return state.ordinal();
    }

    public boolean getCheck() {
        return check;
    }

    public void setCheck(boolean check) {
        this.check = check;
    }

    @Nullable
    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(@Nullable Long groupId) {
        this.groupId = groupId;
    }
}
